version: '3'

services:
  backend:
    build: .
    volumes:
      - .:/backend
    ports:
      - "0.0.0.0:8000:8000"

  frontend:
    restart: always
    build: ./frontend
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - backend
