# Generated by Django 4.0.2 on 2022-02-20 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('is_active', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.IntegerField()),
                ('due_date', models.DateField()),
                ('groups', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todo.groups')),
            ],
        ),
    ]
